import { useState } from 'react';
import { api, time } from '../api';
import { Dialog } from '../detection/Dialog';
import { useStudio } from '../useStudio';
import type { AIEvaluation, AIResult, Moment } from './types';
import { scoreNames } from './types';

const labels:Record<string,string>={NOT_EVALUATED:'Sin evaluar',QUEUED:'En cola',RETRYING:'Reintentando…',EVALUATING:'Evaluando…',EVALUATED:'Evaluado',FAILED:'Falló'};
const qualityLabels:Record<string,string>={HIGH_POTENTIAL:'ALTO POTENCIAL',GOOD:'BUENO',MEDIUM:'MEDIO',LOW:'BAJO'};
const coreScores = Object.fromEntries(Object.entries(scoreNames).filter(([key])=>!['context_dependency_score','completeness_score'].includes(key))) as typeof scoreNames;

function Scores({result,details=false}:{result:AIResult;details?:boolean}) {
  const fields=details?scoreNames:coreScores;
  return <div className="ai-scores">{Object.entries(fields).map(([key,label])=>{const value=result[key as keyof AIResult] as number;return <div key={key}><span>{label}</span><progress aria-label={label} max={10} value={value}/><b>{value.toFixed(1)}</b></div>;})}</div>;
}

function latestFor(evaluations:AIEvaluation[],id:string){return evaluations.find(row=>row.moment_id===id);}

export function AIOverview({studio,liveOnly=false}:{studio:ReturnType<typeof useStudio>;liveOnly?:boolean}) {
  const current=studio.moments.filter(moment=>!liveOnly||moment.stream_id===studio.stream.stream_id);
  const stats=studio.aiStatistics;
  return <div className="ai-overview"><span>Detección <b>{studio.detection?.active_rule_count?(studio.stream.state==='live'?'ACTIVA':'LISTA'):'SIN REGLAS'}</b></span><span>IA <b>{studio.ai?.status||'OFFLINE'}</b></span><span>Cola <b>{studio.ai?.queued||0}</b></span><span>Candidatos <b>{liveOnly?current.length:stats?.candidates||0}</b></span><span>Alto potencial <b>{stats?.high_potential||0}</b></span><small>{studio.ai?.evaluation_mode==='AUTOMATIC'?'Evaluación automática':'Evaluación manual'} · procesamiento local</small></div>;
}

function TopMoments({studio}:{studio:ReturnType<typeof useStudio>}) {
  if(!studio.aiRanking.length)return null;
  return <section className="panel top-moments"><div><span className="eyebrow">MOMENT RANKING</span><h2>Mejores momentos</h2></div><ol>{studio.aiRanking.map(row=><li key={row.moment_id}><b>#{row.rank}</b><span>{row.moment_summary}</span><strong>{row.overall_score.toFixed(1)}<small>/10</small></strong><em>{qualityLabels[row.quality_level]||row.quality_level}</em></li>)}</ol></section>;
}

export function MomentsPage({studio}:{studio:ReturnType<typeof useStudio>}) {
  const [filter,setFilter]=useState('all'),[minimum,setMinimum]=useState(0),[sort,setSort]=useState('newest');
  const [selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<Moment|null>(null),[preview,setPreview]=useState<Moment|null>(null);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const latest=(id:string)=>latestFor(studio.evaluations,id);
  async function action(path:string,body:unknown={}) {setBusy(true);setMessage('');try{await api(path,body);setMessage('Solicitud completada.');}catch(error){setMessage(error instanceof Error?error.message:'Ocurrió un error.');}finally{setBusy(false);}}
  async function batch(){setBusy(true);try{const rows=await api<{error?:string}[]>('/ai/evaluate-batch',{moment_ids:selected});const failures=rows.filter(row=>row.error);setMessage(`${rows.length-failures.length} enviados a evaluación.${failures.length?` ${failures.map(row=>row.error).join(' ')}`:''}`);setSelected([]);}catch(error){setMessage(error instanceof Error?error.message:'No se pudo encolar.');}finally{setBusy(false);}}
  const visible=studio.moments.filter(moment=>{const evaluation=latest(moment.id),result=evaluation?.result,status=evaluation?.status||'NOT_EVALUATED';if(minimum>0&&(!result||result.overall_score<minimum))return false;return filter==='all'||filter==='NOT_EVALUATED'&&status==='NOT_EVALUATED'||filter==='EVALUATING'&&['QUEUED','EVALUATING','RETRYING'].includes(status)||filter==='FAILED'&&status==='FAILED'||filter===result?.quality_level;}).sort((left,right)=>sort==='newest'?right.created_at.localeCompare(left.created_at):sort==='detection'?right.detection_confidence-left.detection_confidence:Number(latest(right.id)?.result?.[sort as keyof AIResult]??-1)-Number(latest(left.id)?.result?.[sort as keyof AIResult]??-1));
  const history=detail?studio.evaluations.filter(row=>row.moment_id===detail.id):[];
  return <><AIOverview studio={studio}/><TopMoments studio={studio}/><p className="ai-help">La detección responde “¿hay un posible momento?”. La IA responde “¿qué tan bueno es?”. Sus métricas no se mezclan y ningún score crea un clip automáticamente.</p>
    <div className="ai-toolbar"><label>Mostrar<select value={filter} onChange={event=>setFilter(event.target.value)}>{[['all','Todos'],['NOT_EVALUATED','Sin evaluar'],['EVALUATING','Evaluando'],['HIGH_POTENTIAL','Alto potencial'],['GOOD','Buenos'],['MEDIUM','Medios'],['LOW','Bajos'],['FAILED','Fallidos']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Nota mínima<input type="number" min={0} max={10} step={.5} value={minimum} onChange={event=>setMinimum(Number(event.target.value))}/></label><label>Ordenar<select value={sort} onChange={event=>setSort(event.target.value)}>{[['newest','Más recientes'],['overall_score','Nota final'],['virality_score','Potencial de compartir'],['interest_score','Interés'],['detection','Confianza de detección']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button className="primary" disabled={busy||!selected.length} onClick={()=>void batch()}>Evaluar seleccionados ({selected.length})</button></div>
    {message&&<div className="notice" role="status">{message}</div>}{!visible.length&&<section className="panel ai-empty"><h2>{studio.moments.length?'No hay resultados con estos filtros.':'Aquí aparecerán tus candidatos.'}</h2><p>{studio.moments.length?'Prueba otro filtro o reduce la nota mínima.':'Activa tus reglas en Settings → Moment Detection y conecta un directo. Los candidatos se conservan aunque Ollama esté apagado.'}</p></section>}
    <div className="moments-grid">{visible.map(moment=>{const evaluation=latest(moment.id),result=evaluation?.result,status=evaluation?.status||'NOT_EVALUATED';return <article className="panel moment-card" key={moment.id}><div className="moment-heading"><label><input type="checkbox" checked={selected.includes(moment.id)} onChange={event=>setSelected(event.target.checked?[...selected,moment.id]:selected.filter(id=>id!==moment.id))}/>{moment.moment_type.replaceAll('_',' ')}</label><small>{time(moment.start)} → {time(moment.end)}</small></div>{moment.id.startsWith('example-')&&<small>Ejemplo con captura anterior y regla temporal de prueba. Tus reglas no se modificaron.</small>}<p className="moment-excerpt">{result?.moment_summary||moment.transcript_excerpt}</p><div className="moment-confidence">Confianza de detección <b>{Math.round(moment.detection_confidence*100)}%</b></div><div className="moment-ai-label">IA · {labels[status]||status}</div>{result&&<><Scores result={result}/><div className={`moment-overall ${result.quality_level==='HIGH_POTENTIAL'?'high':''}`}><span>{qualityLabels[result.quality_level]}</span><b>{result.overall_score.toFixed(1)}<small> / 10</small></b></div><small>Recomendación del backend: {({CREATE_CLIP:'crear clip',REVIEW:'revisar',DISCARD:'descartar'} as Record<string,string>)[result.recommended_action]}</small></>}{evaluation?.error_message&&<p className="notice error">{evaluation.error_message}</p>}{moment.status==='DISMISSED'&&<small>Descartado por el usuario</small>}<div className="ai-actions"><button className="secondary" disabled={busy||['QUEUED','EVALUATING','RETRYING'].includes(status)||moment.status==='DISMISSED'} onClick={()=>void action(`/moments/${moment.id}/${evaluation?'reevaluate':'evaluate'}`)}>{status==='FAILED'?'Reintentar':evaluation?'Reevaluar':'Evaluar con IA'}</button><button className="secondary" disabled={moment.media_status!=='READY'} onClick={()=>setPreview(moment)}>Preview</button><button className="primary" disabled={busy||moment.media_status!=='READY'} onClick={()=>void action(`/moments/${moment.id}/clip`)}>{moment.clip_id?'Clip guardado':'Crear clip'}</button><button className="secondary" onClick={()=>setDetail(moment)}>Detalles</button></div>{moment.media_status!=='READY'&&<small>{moment.media_error||'Preparando video…'}</small>}</article>;})}</div>
    {preview&&<Dialog title="Preview del momento" close={()=>setPreview(null)}><video className="moment-video" controls autoPlay src={`/api/moments/${preview.id}/video`}/></Dialog>}
    {detail&&<Dialog title="Detalle del momento" close={()=>setDetail(null)}><div className="ai-details"><p>{detail.transcript_excerpt}</p><p>Detección: {Math.round(detail.detection_confidence*100)}% · {time(detail.start)} → {time(detail.end)}</p><details><summary>Razones de detección</summary><pre>{JSON.stringify(detail.detection_reasons,null,2)}</pre></details><p>Reevaluar crea un nuevo historial y usa el proveedor, modelo y ajustes actuales.</p><button className="primary" disabled={busy} onClick={()=>void action(`/moments/${detail.id}/reevaluate`)}>Reevaluar</button>{history.length===0&&<p>Aún no hay evaluaciones.</p>}{history.map(evaluation=><EvaluationHistory key={evaluation.id} evaluation={evaluation} moment={detail} busy={busy} action={action}/>) }{message&&<p role="status">{message}</p>}</div></Dialog>}
  </>;
}

function EvaluationHistory({evaluation,moment,busy,action}:{evaluation:AIEvaluation;moment:Moment;busy:boolean;action:(path:string,body?:unknown)=>Promise<void>}){const result=evaluation.result;return <section className="ai-history"><h3>{evaluation.model} · {labels[evaluation.status]||evaluation.status}</h3><small>{evaluation.provider} · {evaluation.evaluation_version} · {evaluation.latency_ms} ms · {evaluation.attempts} intentos · {new Date(evaluation.created_at).toLocaleString()}{evaluation.input_tokens!==null?` · ${evaluation.input_tokens} entrada / ${evaluation.output_tokens||0} salida tokens`:''}</small>{result&&<><div className="ai-details-score"><span>Overall</span><strong>{result.overall_score.toFixed(1)} / 10</strong><em>{qualityLabels[result.quality_level]}</em></div><p>{result.moment_summary}</p><dl>{Object.entries({Tema:result.detected_topic,Tipo:result.content_type,Tono:result.emotional_tone,'Necesita contexto':result.requires_context?'Sí':'No',Motivo:result.evaluation_reason,Recomendación:result.recommended_action}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><Scores result={result} details/></>}{evaluation.error_message&&<p className="notice error">{evaluation.error_message}</p>}<div className="ai-actions">{[['THUMBS_UP','Útil'],['THUMBS_DOWN','No útil'],['APPROVED','Aprobar'],['DISMISSED','Descartar']].map(([value,label])=><button className="secondary" disabled={busy} key={value} onClick={()=>void action(`/moments/${moment.id}/feedback`,{evaluation_id:evaluation.id,action:value})}>{label}</button>)}</div></section>;}
