import { useEffect, useState } from "react";
import { CalendarClock, Check, Send, ShieldCheck } from "lucide-react";
import { api } from "../api";
import type { ContentMetadata, PlatformCapability, PublicationJob, PublishingStatus, SocialAccount, SocialPlatform } from "../types";
import { Status } from "./PublishingPage";

const platforms: {id:SocialPlatform;label:string}[]=[{id:"tiktok",label:"TikTok"},{id:"youtube",label:"YouTube Shorts"},{id:"instagram",label:"Instagram Reels"},{id:"facebook",label:"Facebook Reels"}];

export function PublishPanel({clipId,notify}:{clipId:string;notify:(value:string)=>void}) {
  const [accounts,setAccounts]=useState<SocialAccount[]>([]),[caps,setCaps]=useState<PlatformCapability[]>([]),[status,setStatus]=useState<PublishingStatus|null>(null),[metadata,setMetadata]=useState<ContentMetadata|null>(null),[jobs,setJobs]=useState<PublicationJob[]>([]);
  const [selected,setSelected]=useState<SocialPlatform[]>([]),[accountIds,setAccountIds]=useState<Partial<Record<SocialPlatform,string>>>({}),[overrides,setOverrides]=useState<Partial<Record<SocialPlatform,Record<string,string|string[]>>>>({});
  const [mode,setMode]=useState<"now"|"schedule">("now"),[date,setDate]=useState(""),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false);
  const load=()=>Promise.all([api<SocialAccount[]>("/publishing/accounts"),api<PlatformCapability[]>("/publishing/capabilities"),api<PublishingStatus>("/publishing/status"),api<ContentMetadata>(`/clips/${clipId}/metadata`),api<PublicationJob[]>(`/publishing/jobs?clip_id=${clipId}`)])
    .then(([a,c,s,m,j])=>{setAccounts(a);setCaps(c);setStatus(s);setMetadata(m);setJobs(j);setAccountIds((current)=>{const next={...current};for(const p of platforms){const match=a.find(row=>row.platform===p.id&&row.status==="CONNECTED"&&row.provider_mode===(s.safe_publish_mode?"mock":"real"));if(match&&!next[p.id])next[p.id]=match.id;}return next;});});
  useEffect(()=>{void load().catch(()=>undefined);const timer=setInterval(()=>void load().catch(()=>undefined),2500);return()=>clearInterval(timer);},[clipId]);
  const toggle=(platform:SocialPlatform)=>setSelected(current=>current.includes(platform)?current.filter(item=>item!==platform):[...current,platform]);
  const platformMetadata=(platform:SocialPlatform):Record<string,string|string[]>=>{if(!metadata?.platforms)return{};const key={youtube:"youtube_shorts",tiktok:"tiktok",instagram:"instagram_reels",facebook:"facebook_reels"}[platform] as keyof typeof metadata.platforms;return metadata.platforms[key] as unknown as Record<string,string|string[]>;};
  const preview=selected[0], previewData=preview?{...platformMetadata(preview),...(overrides[preview]||{})}:null;
  async function publish(){if(!confirm){setConfirm(true);return;}setBusy(true);try{const payload={clip_id:clipId,platforms:selected.map(platform=>({platform,account_id:accountIds[platform],overrides:overrides[platform]||{}})),scheduled_at:mode==="schedule"&&date?new Date(date).toISOString():null};const rows=await api<PublicationJob[]>("/publishing/jobs",payload);setJobs(current=>[...rows,...current]);notify(mode==="schedule"?"Publicación programada.":"Publicación añadida a la cola.");setConfirm(false);setSelected([]);}catch(error){notify(error instanceof Error?error.message:"No se pudo publicar.");}finally{setBusy(false);}}
  const ready=metadata?.publication_status==="READY_TO_PUBLISH";
  return <section className="publish-panel"><div className="metadata-heading"><div><span>DISTRIBUTION</span><h3>Publish clip</h3></div>{status?.safe_publish_mode&&<span className="metadata-ready ready"><ShieldCheck size={13}/> SAFE MODE</span>}</div>
    {!ready&&<p className="notice">Guarda primero la metadata para dejar el clip READY TO PUBLISH.</p>}
    <div className="publish-platforms">{platforms.map(({id,label})=>{const cap=caps.find(item=>item.platform===id),available=!!accountIds[id]&&!!cap?.capabilities.publish_now;return <label className={`${selected.includes(id)?"selected":""} ${!available?"disabled":""}`} key={id}><input type="checkbox" checked={selected.includes(id)} disabled={!ready||!available} onChange={()=>toggle(id)}/><span className={`platform-mark ${id}`}>{id[0].toUpperCase()}</span><span><b>{label}</b><small>{available?accounts.find(a=>a.id===accountIds[id])?.display_name:cap?.configuration_required||"NOT CONNECTED"}</small></span></label>})}</div>
    {preview&&previewData&&<div className="publish-preview"><span>PUBLICATION OVERRIDE · {preview.toUpperCase()}</span>{"title" in previewData&&<label>Title<input value={String(previewData.title||"")} onChange={e=>setOverrides({...overrides,[preview]:{...(overrides[preview]||{}),title:e.target.value}})}/></label>}<label>{"caption" in previewData?"Caption":"Description"}<textarea rows={2} value={String(("caption" in previewData?previewData.caption:previewData.description)||"")} onChange={e=>{const key="caption" in previewData?"caption":"description";setOverrides({...overrides,[preview]:{...(overrides[preview]||{}),[key]:e.target.value}})}}/></label><label>Hashtags<input value={(previewData.hashtags as string[]||[]).join(" ")} onChange={e=>setOverrides({...overrides,[preview]:{...(overrides[preview]||{}),hashtags:e.target.value.split(/[\s,]+/).filter(Boolean)}})}/></label><small>Este cambio solo afecta esta publicación; no modifica la metadata general.</small></div>}
    <div className="publish-mode"><label><input type="radio" checked={mode==="now"} onChange={()=>setMode("now")}/><Send size={14}/> Publish now</label><label><input type="radio" checked={mode==="schedule"} onChange={()=>setMode("schedule")}/><CalendarClock size={14}/> Schedule</label>{mode==="schedule"&&<input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/>}</div>
    {confirm&&<div className="publish-confirm"><Check size={17}/><div><strong>Confirma la distribución</strong><p>Vas a {mode==="schedule"?"programar":"publicar"} este clip en {selected.map(p=>p.toUpperCase()).join(", ")}. {status?.safe_publish_mode?"Es una simulación segura.":"Esta acción es real."}</p></div><button onClick={()=>setConfirm(false)}>Cancelar</button></div>}
    <button className="primary publish-submit" disabled={!ready||!selected.length||busy||(mode==="schedule"&&!date)} onClick={()=>void publish()}>{busy?"Procesando…":confirm?"Confirmar publicación":mode==="schedule"?"Programar":"Continuar"}</button>
    {!!jobs.length&&<div className="clip-publications">{jobs.map(job=><div key={job.id}><span>{job.platform}</span><Status status={job.status}/>{job.publication_url&&<a href={job.publication_url} target="_blank" rel="noreferrer">Abrir</a>}</div>)}</div>}
  </section>;
}
